import { useEffect, useState } from "react";
import { Plus, Pencil, Trash2, ShieldCheck } from "lucide-react";
import { type InsurancePolicy, INSURERS, formatCurrency } from "@/data/fixedDeposits";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { toast } from "sonner";

type Form = Omit<InsurancePolicy, "id" | "premium" | "sumAssured"> & { premium: string; sumAssured: string };
const empty: Form = { policyNo: "", insurer: "", policyType: "", insuredName: "", premium: "", premiumFrequency: "Yearly", startDate: "", renewalDate: "", sumAssured: "", notes: "" };

interface Props { policies: InsurancePolicy[]; onAdd: (p: InsurancePolicy) => void; onUpdate: (p: InsurancePolicy) => void; onDelete: (id: string) => void; }

const InsurancePolicies = ({ policies, onAdd, onUpdate, onDelete }: Props) => {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<InsurancePolicy | null>(null); const [form, setForm] = useState<Form>(empty); const [review, setReview] = useState<InsurancePolicy | null>(null); const [deleting, setDeleting] = useState<InsurancePolicy | null>(null);
  useEffect(() => { if (!open) return; setForm(editing ? { ...editing, premium: String(editing.premium), sumAssured: editing.sumAssured ? String(editing.sumAssured) : "", notes: editing.notes ?? "" } : empty); }, [open, editing]);
  const update = (key: keyof Form, value: string) => setForm((f) => ({ ...f, [key]: value }));
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!form.policyNo.trim() || !form.insurer || !form.policyType.trim() || !form.insuredName.trim() || !form.startDate || !form.renewalDate) return toast.error("Please complete all required policy details."); if (new Date(form.renewalDate) < new Date(form.startDate)) return toast.error("Renewal date must be on or after the start date."); const premium = Number(form.premium); if (!premium || premium <= 0) return toast.error("Premium must be greater than 0."); setReview({ id: editing?.id ?? crypto.randomUUID(), policyNo: form.policyNo.trim(), insurer: form.insurer, policyType: form.policyType.trim(), insuredName: form.insuredName.trim(), premium, premiumFrequency: form.premiumFrequency, startDate: form.startDate, renewalDate: form.renewalDate, sumAssured: form.sumAssured ? Number(form.sumAssured) : undefined, notes: form.notes.trim() || undefined }); };
  const save = () => { if (!review) return; editing ? onUpdate(review) : onAdd(review); setReview(null); setOpen(false); setEditing(null); };
  const startEdit = (p: InsurancePolicy) => { setEditing(p); setOpen(true); };
  return <section className="rounded-md sm:rounded-xl bg-card border border-border shadow-[var(--shadow-card)] overflow-hidden">
    <div className="p-3 sm:p-5 border-b border-border flex items-center justify-between gap-3"><div><h2 className="text-base sm:text-xl font-display flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-primary" />Insurance Policies</h2><p className="text-xs sm:text-sm text-muted-foreground mt-1">{policies.length} polic{policies.length === 1 ? "y" : "ies"} tracked</p></div><Dialog open={open} onOpenChange={(v) => { setOpen(v); if (!v) setEditing(null); }}><DialogTrigger asChild><Button size="sm" className="gap-1.5"><Plus className="w-4 h-4" /> Add policy</Button></DialogTrigger><DialogContent className="w-[calc(100vw-1rem)] max-h-[94vh] overflow-y-auto sm:max-w-lg"><DialogHeader><DialogTitle>{editing ? "Edit insurance policy" : "Add insurance policy"}</DialogTitle></DialogHeader><form onSubmit={submit} className="grid grid-cols-2 gap-3 pt-2"><div><Label>Policy number *</Label><Input value={form.policyNo} onChange={(e) => update("policyNo", e.target.value)} /></div><div><Label>Insurer *</Label><Select value={form.insurer} onValueChange={(v) => update("insurer", v)}><SelectTrigger><SelectValue placeholder="Select insurer" /></SelectTrigger><SelectContent>{INSURERS.map((i) => <SelectItem key={i} value={i}>{i}</SelectItem>)}</SelectContent></Select></div><div><Label>Policy type *</Label><Input value={form.policyType} onChange={(e) => update("policyType", e.target.value)} placeholder="Health, life, vehicle..." /></div><div><Label>Insured person *</Label><Input value={form.insuredName} onChange={(e) => update("insuredName", e.target.value)} /></div><div><Label>Premium (₹) *</Label><Input type="number" value={form.premium} onChange={(e) => update("premium", e.target.value)} /></div><div><Label>Frequency</Label><Select value={form.premiumFrequency} onValueChange={(v) => update("premiumFrequency", v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["Monthly", "Quarterly", "Half-Yearly", "Yearly"].map((f) => <SelectItem key={f} value={f}>{f}</SelectItem>)}</SelectContent></Select></div><div><Label>Start date *</Label><Input type="date" value={form.startDate} onChange={(e) => update("startDate", e.target.value)} /></div><div><Label>Renewal / expiry date *</Label><Input type="date" value={form.renewalDate} onChange={(e) => update("renewalDate", e.target.value)} /></div><div className="col-span-2"><Label>Sum assured (₹, optional)</Label><Input type="number" value={form.sumAssured} onChange={(e) => update("sumAssured", e.target.value)} /></div><div className="col-span-2"><Label>Notes (optional)</Label><Textarea rows={2} value={form.notes} onChange={(e) => update("notes", e.target.value)} /></div><Button className="col-span-2" type="submit">Review before saving</Button></form></DialogContent></Dialog></div>
    <div className="divide-y divide-border">{policies.length === 0 ? <p className="p-8 text-center text-sm text-muted-foreground">No insurance policies added yet.</p> : policies.map((p) => <div key={p.id} className="p-3 sm:px-5 sm:py-4 flex items-center justify-between gap-3"><div className="min-w-0"><p className="font-medium truncate">{p.policyType} · {p.insurer}</p><p className="text-xs text-muted-foreground">{p.insuredName} · Policy {p.policyNo} · Renews {p.renewalDate}</p><p className="text-sm mt-1">{formatCurrency(p.premium)} <span className="text-muted-foreground text-xs">/ {p.premiumFrequency.toLowerCase()}</span>{p.sumAssured ? <span className="text-muted-foreground text-xs"> · Cover {formatCurrency(p.sumAssured)}</span> : null}</p></div><div className="flex shrink-0"><Button variant="ghost" size="icon" onClick={() => startEdit(p)}><Pencil className="w-4 h-4" /></Button><Button variant="ghost" size="icon" className="text-destructive" onClick={() => setDeleting(p)}><Trash2 className="w-4 h-4" /></Button></div></div>)}</div>
    <AlertDialog open={!!review} onOpenChange={(v) => !v && setReview(null)}><AlertDialogContent className="w-[calc(100vw-2rem)] max-w-md"><AlertDialogHeader><AlertDialogTitle>Review insurance policy</AlertDialogTitle><AlertDialogDescription>Confirm the policy details before saving.</AlertDialogDescription></AlertDialogHeader>{review && <div className="grid grid-cols-2 gap-2 rounded-lg bg-muted/50 p-3 text-sm"><span className="text-muted-foreground">Policy</span><span className="text-right font-medium">{review.policyNo}</span><span className="text-muted-foreground">Insurer / type</span><span className="text-right font-medium">{review.insurer} · {review.policyType}</span><span className="text-muted-foreground">Premium</span><span className="text-right font-medium">{formatCurrency(review.premium)} / {review.premiumFrequency}</span><span className="text-muted-foreground">Renewal</span><span className="text-right font-medium">{review.renewalDate}</span></div>}<AlertDialogFooter><AlertDialogCancel>Go back</AlertDialogCancel><AlertDialogAction onClick={save}>Confirm & save</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={!!deleting} onOpenChange={(v) => !v && setDeleting(null)}><AlertDialogContent className="w-[calc(100vw-2rem)] max-w-md"><AlertDialogHeader><AlertDialogTitle>Delete this insurance policy?</AlertDialogTitle><AlertDialogDescription>This will permanently remove policy {deleting?.policyNo}.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={() => { if (deleting) onDelete(deleting.id); setDeleting(null); }}>Delete policy</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </section>;
};
export default InsurancePolicies;
